from __future__ import annotations

from pathlib import Path

TEST = Path("tests/test_recursive_research_cycle_evidence.py")
text = TEST.read_text(encoding="utf-8")
old = '''def test_repeated_authenticated_successor_graph_is_no_new_information(tmp_path: Path) -> None:\n    plan = _plan()\n    checkpoint = _checkpoint(plan)\n    bundle, result_sha = _bundle(tmp_path)\n    execution = _execution(checkpoint, result_sha)\n    first = advance_recursive_cycle_after_verified_transition(\n        authorization_checkpoint=checkpoint,\n        verified_execution_record=execution,\n        transition_bundle_root=bundle,\n        fresh_plan=plan,\n        program_state={"workstreams": []},\n    )\n    with pytest.raises(RecursiveResearchEvidenceError, match="no new evaluated graph"):\n        advance_recursive_cycle_after_verified_transition(\n            authorization_checkpoint=checkpoint,\n            verified_execution_record=execution,\n            transition_bundle_root=bundle,\n            fresh_plan=plan,\n            program_state={"workstreams": []},\n            previous_progression=first,\n        )\n'''
new = '''def test_cycle_one_rejects_predecessor_progression(tmp_path: Path) -> None:\n    plan = _plan()\n    checkpoint = _checkpoint(plan)\n    bundle, result_sha = _bundle(tmp_path)\n    execution = _execution(checkpoint, result_sha)\n    first = advance_recursive_cycle_after_verified_transition(\n        authorization_checkpoint=checkpoint,\n        verified_execution_record=execution,\n        transition_bundle_root=bundle,\n        fresh_plan=plan,\n        program_state={"workstreams": []},\n    )\n    with pytest.raises(\n        RecursiveResearchEvidenceError,\n        match="cycle-one progression cannot accept a predecessor progression",\n    ):\n        advance_recursive_cycle_after_verified_transition(\n            authorization_checkpoint=checkpoint,\n            verified_execution_record=execution,\n            transition_bundle_root=bundle,\n            fresh_plan=plan,\n            program_state={"workstreams": []},\n            previous_progression=first,\n        )\n'''
if text.count(old) != 1:
    raise SystemExit(f"expected old cycle-one replay regression once, found {text.count(old)}")
TEST.write_text(text.replace(old, new, 1), encoding="utf-8")
